name: Build and Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
      - name: Build documentation with sphinx and uv
        run: uv tool run --from sphinx --with-requirements docs/requirements.txt --with-editable "." sphinx-build -M html docs/source docs/build
